import type { GesturePreset, HardwareButton } from '../types.js';
import { ANDROID_BUTTONS } from '../types.js';
import type { SwipeSpec, TapSelector, UiDriver } from '../device.js';
import type { Screen, UiElement } from '../screen.js';
import { ALWAYS_KEEP, NOISE_TYPES, clean, finishScreen } from '../screen.js';
import { sleep } from '../util.js';
import type { Adb } from './adb.js';
import { logger } from '../log.js';

const log = logger('uiautomator');

/** Where the dump is written on the device before being read back. */
const DUMP_PATH = '/data/local/tmp/simcheck-dump.xml';

/** Failures that mean "the screen would not hold still", not "the app is wrong". */
const TRANSIENT = /could not get idle state|null root node|ERROR: could not get idle|UiAutomation not connected|Killed/i;

/**
 * Android keycodes, by the name the harness uses.
 * `input keyevent` accepts the numeric code on every version, and the symbolic
 * name only on some, so the numbers are what we send.
 */
const KEYCODE: Record<string, number> = {
  home: 3,
  back: 4,
  menu: 82,
  recents: 187,        // KEYCODE_APP_SWITCH
  power: 26,
  'volume-up': 24,
  'volume-down': 25,
  enter: 66,
  del: 67,
  'move-end': 123,
};

/**
 * Maps an Android widget class onto the harness's normalised role vocabulary.
 *
 * The point is that a step written against an iOS run reads the same on
 * Android: `{"action":"tap","label":"Save"}` should not need to know that one
 * platform calls it a Button and the other an android.widget.Button. Anything
 * unrecognised keeps its leaf class name, which is more useful than "Unknown".
 */
const ROLE: Array<[RegExp, string]> = [
  [/\.Button$|\.ImageButton$|\.AppCompatButton$|MaterialButton/, 'Button'],
  [/\.EditText$|TextInputEditText|AppCompatEditText/, 'TextField'],
  [/\.CheckBox$|\.AppCompatCheckBox$|MaterialCheckBox/, 'CheckBox'],
  [/\.RadioButton$/, 'RadioButton'],
  [/\.Switch$|SwitchCompat|SwitchMaterial/, 'Switch'],
  [/\.ToggleButton$/, 'Switch'],
  [/\.SeekBar$|\.Slider$/, 'Slider'],
  [/\.Spinner$|\.NumberPicker$/, 'Picker'],
  [/\.ImageView$/, 'Image'],
  [/\.TextView$|\.AppCompatTextView$/, 'StaticText'],
  [/\.RecyclerView$|\.ListView$|\.ScrollView$|NestedScrollView|\.GridView$/, 'ScrollView'],
  [/\.ViewPager/, 'ScrollView'],
  [/TabLayout|\.TabWidget$/, 'TabBar'],
  [/\.Toolbar$|ActionBar/, 'NavigationBar'],
  [/\.WebView$/, 'WebView'],
  [/\.ProgressBar$/, 'ProgressIndicator'],
  [/\.FrameLayout$|\.LinearLayout$|\.RelativeLayout$|ConstraintLayout|\.ViewGroup$/, 'Group'],
];

export function normaliseRole(cls: string): string {
  for (const [pattern, role] of ROLE) if (pattern.test(cls)) return role;
  return cls.split('.').pop() || 'Unknown';
}

/** `bounds="[0,0][1080,2400]"` -> a frame. */
export function parseBounds(bounds: string): { x: number; y: number; width: number; height: number } | null {
  const m = bounds.match(/\[(-?\d+),(-?\d+)\]\[(-?\d+),(-?\d+)\]/);
  if (!m) return null;
  const [x1, y1, x2, y2] = [Number(m[1]), Number(m[2]), Number(m[3]), Number(m[4])];
  return { x: x1!, y: y1!, width: x2! - x1!, height: y2! - y1! };
}

const XML_ENTITIES: Record<string, string> = {
  '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&apos;': "'",
};

const unescapeXml = (s: string): string =>
  s.replace(/&(amp|lt|gt|quot|apos);/g, (m) => XML_ENTITIES[m] ?? m)
   .replace(/&#(\d+);/g, (_, d: string) => String.fromCodePoint(Number(d)));

/**
 * Parse a `uiautomator dump` hierarchy.
 *
 * Hand-rolled rather than pulling in an XML dependency: the input is
 * machine-generated by a single known producer, every attribute is
 * double-quoted, and the only nesting that matters is `<node>`. A general
 * parser would be more code and no more correct against this one format.
 */
export function parseHierarchy(xml: string, cap = 120): Screen {
  const collected: UiElement[] = [];
  let rootFrame: { width: number; height: number } | null = null;
  let depth = 0;

  // Each match is one node's opening tag; `/>` means it has no children.
  const tag = /<node\s([^>]*?)(\/?)>|<\/node>/g;
  for (let m = tag.exec(xml); m; m = tag.exec(xml)) {
    if (m[0] === '</node>') { depth--; continue; }

    const attrs = m[1] ?? '';
    const selfClosing = m[2] === '/';
    const attr = (name: string): string => {
      const hit = attrs.match(new RegExp(`\\b${name}="([^"]*)"`));
      return hit ? unescapeXml(hit[1]!) : '';
    };

    const frame = parseBounds(attr('bounds'));
    if (frame) {
      rootFrame ??= { width: frame.width, height: frame.height };

      const cls = attr('class');
      const type = normaliseRole(cls);
      // content-desc is the accessibility label proper; text is what is drawn.
      const label = clean(attr('content-desc')) ?? clean(attr('text'));
      // resource-id arrives as "com.example:id/save_button"; the bare name is
      // what a test author writes, and what matches an iOS identifier in feel.
      const rawId = attr('resource-id');
      const id = clean(rawId.includes('/') ? rawId.split('/').pop() : rawId);
      const text = clean(attr('text'));
      // Only surface `value` where it says something the label does not.
      const value = text && text !== label ? text : undefined;

      const meaningful = Boolean(label || id || value);
      const interactive = ALWAYS_KEEP.has(type) || attr('clickable') === 'true';
      const visible = frame.width > 0 && frame.height > 0;

      if (visible && (interactive || (meaningful && !NOISE_TYPES.has(type)))) {
        collected.push({
          type,
          ...(label ? { label } : {}),
          ...(id ? { id } : {}),
          ...(value ? { value } : {}),
          enabled: attr('enabled') !== 'false',
          center: { x: Math.round(frame.x + frame.width / 2), y: Math.round(frame.y + frame.height / 2) },
          frame: {
            x: Math.round(frame.x), y: Math.round(frame.y),
            width: Math.round(frame.width), height: Math.round(frame.height),
          },
          depth,
        });
      }
    }
    if (!selfClosing) depth++;
  }

  return finishScreen(collected, rootFrame?.width ?? 0, rootFrame?.height ?? 0, cap, 'px');
}

/**
 * Drives an emulator through `adb shell`.
 *
 * Deliberately single-contact: `input` speaks one pointer, so pinch and
 * two-finger pan live in the separate TouchDriver rather than being faked
 * here. A gesture the harness cannot really perform must fail, not approximate.
 */
export class UiAutomator implements UiDriver {
  constructor(private adb: Adb, private avd: string) {}

  private async serial(): Promise<string> { return this.adb.serialFor(this.avd); }

  /** Retry only the "screen would not hold still" failures, so a genuinely
   *  missing element still surfaces immediately. */
  private async withRetry<T>(what: string, fn: () => Promise<T>, signal?: AbortSignal): Promise<T> {
    let lastError: Error | undefined;
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        return await fn();
      } catch (e) {
        lastError = e as Error;
        if (!TRANSIENT.test(lastError.message) || signal?.aborted) throw lastError;
        log.warn(`${what} was not idle, retrying`, lastError.message.slice(0, 120));
        await sleep(1500 * (attempt + 1), signal);
      }
    }
    throw lastError!;
  }

  async describe(signal?: AbortSignal, cap = 120): Promise<Screen> {
    const serial = await this.serial();
    return this.withRetry('uiautomator dump', async () => {
      const dumped = await this.adb.shellTry(serial, `uiautomator dump ${DUMP_PATH}`, {
        timeoutMs: 45_000, ...(signal ? { signal } : {}),
      });
      // It reports failure in prose on a zero exit as often as via the code.
      if (dumped.code !== 0 || /ERROR|could not/i.test(dumped.out)) {
        throw new Error(`uiautomator dump failed: ${dumped.out.trim().slice(0, 300)}`);
      }
      // exec-out, not shell: the shell pty would rewrite newlines in the XML.
      const xml = await this.adb.raw(serial, ['exec-out', 'cat', DUMP_PATH], {
        timeoutMs: 45_000, ...(signal ? { signal } : {}),
      });
      if (!xml.includes('<hierarchy')) {
        throw new Error(`uiautomator dump produced no hierarchy: ${xml.slice(0, 300)}`);
      }
      return parseHierarchy(xml, cap);
    }, signal);
  }

  async screenshot(outPath: string, signal?: AbortSignal): Promise<void> {
    const serial = await this.serial();
    if (signal?.aborted) throw new Error('cancelled');
    await this.adb.execOutToFile(serial, ['screencap', '-p'], outPath, 60_000);
  }

  /** Resolve a selector to a point, since `input tap` only speaks coordinates. */
  private async locate(sel: TapSelector, signal?: AbortSignal): Promise<{ x: number; y: number }> {
    if (sel.x !== undefined && sel.y !== undefined) return { x: sel.x, y: sel.y };

    const deadline = Date.now() + (sel.waitTimeoutMs ?? 5000);
    let seen: Screen | null = null;
    for (;;) {
      seen = await this.describe(signal);
      const hit = seen.elements.find((e) => matches(e, sel));
      if (hit) return hit.center;
      if (Date.now() >= deadline || signal?.aborted) break;
      await sleep(500, signal);
    }
    const target = sel.id ? `id "${sel.id}"` : sel.label ? `label "${sel.label}"` : `value "${sel.value}"`;
    const nearby = (seen?.elements ?? []).slice(0, 8)
      .map((e) => e.label ?? e.id ?? e.type).join(', ');
    throw new Error(
      `no element matching ${target} appeared within ${sel.waitTimeoutMs ?? 5000}ms. ` +
      `On screen: ${nearby || 'nothing identifiable'}`);
  }

  async tap(sel: TapSelector, signal?: AbortSignal): Promise<void> {
    const serial = await this.serial();
    const { x, y } = await this.locate(sel, signal);
    await this.adb.shell(serial, `input tap ${Math.round(x)} ${Math.round(y)}`, { ...(signal ? { signal } : {}) });
  }

  /**
   * `input text` is the only typing primitive adb offers, and it is a blunt
   * one: the argument goes through the device shell, and the command itself
   * treats %s as a space. Both have to be handled, and neither can carry a
   * newline -- so that is refused rather than silently dropped.
   */
  async type(text: string, signal?: AbortSignal): Promise<void> {
    const serial = await this.serial();
    if (/[\n\r]/.test(text)) {
      throw new Error(
        '`input text` cannot type a newline. Split the text and use a press_enter step between the parts.');
    }
    const escaped = text
      .replace(/'/g, `'\\''`)      // close, escape, reopen for the device shell
      .replace(/ /g, '%s');        // `input text` reads %s as a space
    await this.adb.shell(serial, `input text '${escaped}'`, { timeoutMs: 120_000, ...(signal ? { signal } : {}) });
  }

  async clearText(signal?: AbortSignal, presses = 60): Promise<void> {
    const serial = await this.serial();
    // Move the caret to the end first: backspacing from the middle of an
    // existing value would leave the tail behind.
    const codes = [KEYCODE['move-end']!, ...Array(presses).fill(KEYCODE['del']!)].join(' ');
    await this.adb.shell(serial, `input keyevent ${codes}`, { timeoutMs: 120_000, ...(signal ? { signal } : {}) });
  }

  async pressEnter(signal?: AbortSignal): Promise<void> {
    const serial = await this.serial();
    await this.adb.shell(serial, `input keyevent ${KEYCODE['enter']}`, { ...(signal ? { signal } : {}) });
  }

  async swipe(a: SwipeSpec, signal?: AbortSignal): Promise<void> {
    const serial = await this.serial();
    const duration = Math.round(a.durationMs ?? 300);
    await this.adb.shell(serial,
      `input swipe ${Math.round(a.startX)} ${Math.round(a.startY)} ${Math.round(a.endX)} ${Math.round(a.endY)} ${duration}`,
      { timeoutMs: 60_000, ...(signal ? { signal } : {}) });
  }

  /**
   * Preset gestures, expressed as swipes.
   *
   * Convention: the name describes which way the *finger* travels, so
   * `scroll-up` drags upward and thereby reveals content further down. Edge
   * swipes start just inside the bezel, which is what system gestures listen
   * for.
   */
  async gesture(
    preset: GesturePreset, screen: { width: number; height: number },
    durationMs?: number, signal?: AbortSignal,
  ): Promise<void> {
    const w = screen.width || 1080;
    const h = screen.height || 2400;
    const cx = Math.round(w / 2), cy = Math.round(h / 2);
    const near = 12;                       // just inside the bezel
    const far = Math.round(h * 0.25);

    const paths: Record<GesturePreset, [number, number, number, number]> = {
      'scroll-up': [cx, cy + far, cx, cy - far],
      'scroll-down': [cx, cy - far, cx, cy + far],
      'scroll-left': [Math.round(w * 0.8), cy, Math.round(w * 0.2), cy],
      'scroll-right': [Math.round(w * 0.2), cy, Math.round(w * 0.8), cy],
      'swipe-from-left-edge': [near, cy, Math.round(w * 0.7), cy],
      'swipe-from-right-edge': [w - near, cy, Math.round(w * 0.3), cy],
      'swipe-from-top-edge': [cx, near, cx, Math.round(h * 0.5)],
      'swipe-from-bottom-edge': [cx, h - near, cx, Math.round(h * 0.5)],
    };
    const [x1, y1, x2, y2] = paths[preset];
    await this.swipe({
      startX: x1, startY: y1, endX: x2, endY: y2,
      durationMs: durationMs ?? 300,
    }, signal);
  }

  async button(button: HardwareButton, durationMs?: number, signal?: AbortSignal): Promise<void> {
    if (!ANDROID_BUTTONS.includes(button)) {
      throw new Error(
        `"${button}" is not a button an Android device has. Android accepts: ${ANDROID_BUTTONS.join(', ')}.`);
    }
    const serial = await this.serial();
    const code = KEYCODE[button];
    if (code === undefined) throw new Error(`no keycode mapped for "${button}"`);
    // `--longpress` is the only duration `input keyevent` understands; a
    // precise hold would need the multi-touch driver.
    const args = durationMs && durationMs >= 500 ? `--longpress ${code}` : String(code);
    await this.adb.shell(serial, `input keyevent ${args}`, { ...(signal ? { signal } : {}) });
  }

  async waitFor(sel: { id?: string; label?: string }, timeoutMs: number, signal?: AbortSignal): Promise<boolean> {
    const deadline = Date.now() + timeoutMs;
    for (;;) {
      const screen = await this.describe(signal).catch(() => null);
      if (screen?.elements.some((e) =>
        (sel.id && e.id === sel.id) ||
        (sel.label && (e.label === sel.label || e.label?.includes(sel.label))))) return true;
      if (Date.now() >= deadline || signal?.aborted) return false;
      await sleep(500, signal);
    }
  }
}

function matches(e: UiElement, sel: TapSelector): boolean {
  if (sel.elementType && e.type.toLowerCase() !== sel.elementType.toLowerCase()) return false;
  if (sel.id) return e.id === sel.id;
  if (sel.label) return e.label === sel.label || Boolean(e.label?.includes(sel.label));
  if (sel.value) return e.value === sel.value;
  return false;
}
